import { CatalogPreset } from '../../types';

export const WIDGET_CATALOG: CatalogPreset[] = [
  // ================= UNIVERSAL (W-01 .. W-14) =================
  {
    id: 'W-01',
    nama: 'Total Pendapatan vs Target RKAP',
    sektor: ['universal'],
    tipeChart: ['kpi', 'bullet-target', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Berapa realisasi pendapatan usaha dibandingkan target RKAP tahun berjalan?',
    deskripsi: 'Membandingkan total omset atau pendapatan usaha dengan pagu RKAP yang telah disahkan Pemda.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'W-02',
    nama: 'Tren Realisasi Belanja Operasional (OpEx)',
    sektor: ['universal'],
    tipeChart: ['line', 'area', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Tampilkan tren pengeluaran operasional per bulan selama 12 bulan terakhir.',
    deskripsi: 'Grafik riwayat pengeluaran rutin bulanan untuk pemeliharaan, gaji, bahan baku, dan utilitas.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'W-03',
    nama: 'Laba Bersih Sebelum Pajak (EBT)',
    sektor: ['universal'],
    tipeChart: ['kpi', 'line'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Juta)',
    queryRagContoh: 'Berapa laba bersih sebelum pajak triwulan ini dan perubahannya dibanding tahun lalu?',
    deskripsi: 'Indikator profitabilitas murni operasional BUMD sebelum beban pajak daerah dan pusat.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'W-04',
    nama: 'Arus Kas Operasional Bersih',
    sektor: ['universal'],
    tipeChart: ['bar', 'line'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Arus kas masuk dan keluar dari kegiatan operasional triwulanan.',
    deskripsi: 'Likuiditas harian dan kemampuan menghasilkan kas riil dari penjualan layanan publik.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'W-05',
    nama: 'Struktur Komposisi Beban Usaha',
    sektor: ['universal'],
    tipeChart: ['donut', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Komposisi beban pegawai, beban operasional, dan beban administrasi.',
    deskripsi: 'Distribusi biaya per kategori untuk mendeteksi inefisiensi pengeluaran internal.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'W-06',
    nama: 'Kontribusi Dividen / Setoran PAD',
    sektor: ['universal'],
    tipeChart: ['kpi', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Berapa deviden yang telah disetor ke kas daerah untuk Pendapatan Asli Daerah?',
    deskripsi: 'Jumlah setoran laba bersih ke APBD Pemerintah Provinsi/Kabupaten/Kota.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'W-07',
    nama: 'Ringkasan Eksekutif Kinerja Triwulan',
    sektor: ['universal'],
    tipeChart: ['narasi'],
    kategori: 'Kepatuhan & Risiko',
    satuan: 'Teks & Sitasi',
    queryRagContoh: 'Buat narasi ringkasan eksekutif capaian kunci dan kendala operasional periode ini.',
    deskripsi: 'Sintesis naratif terstruktur berbasis kutipan laporan resmi Dewan Pengawas dan Direksi.',
    defaultLayout: { w: 12, h: 3 },
  },
  {
    id: 'W-08',
    nama: 'Realisasi Investasi Modal (CapEx)',
    sektor: ['universal'],
    tipeChart: ['bar', 'bullet-target'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Capaian belanja modal pembangunan fasilitas baru vs anggaran.',
    deskripsi: 'Serapan dana investasi pengembangan aset tetap infrastruktur daerah.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'W-09',
    nama: 'Tingkat Kepuasan Pelanggan (IKM)',
    sektor: ['universal'],
    tipeChart: ['kpi', 'donut'],
    kategori: 'Pelayanan',
    satuan: 'Skor Indeks (1-100)',
    queryRagContoh: 'Berapa indeks kepuasan masyarakat (IKM) semester terakhir?',
    deskripsi: 'Hasil survei berkala kepuasan publik terhadap kecepatan dan keramahan layanan BUMD.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'W-10',
    nama: 'Tabel Rekapitulasi Finansial per Unit Kerja',
    sektor: ['universal'],
    tipeChart: ['table'],
    kategori: 'Keuangan',
    satuan: 'Multi-kolom',
    queryRagContoh: 'Tampilkan tabel pendapatan, beban, dan margin seluruh unit/cabang.',
    deskripsi: 'Tabel matriks komparasi kinerja antar cabang / unit kerja wilayah.',
    defaultLayout: { w: 12, h: 5 },
  },
  {
    id: 'W-11',
    nama: 'Tingkat Penyelesaian Keluhan Pelanggan',
    sektor: ['universal'],
    tipeChart: ['donut', 'bar'],
    kategori: 'Pelayanan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa persen aduan pelanggan yang selesai ditindaklanjuti dalam SLA < 24 jam?',
    deskripsi: 'Rasio tiket keluhan warga yang terselesaikan tepat waktu oleh unit customer care.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'W-12',
    nama: 'Rasio Produktivitas Pegawai',
    sektor: ['universal'],
    tipeChart: ['kpi', 'line'],
    kategori: 'Operasional',
    satuan: 'Juta Rp / Pegawai',
    queryRagContoh: 'Rata-rata pendapatan yang dihasilkan per karyawan per bulan.',
    deskripsi: 'Efisiensi beban SDM terhadap perolehan pendapatan bruto instansi.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'W-13',
    nama: 'Daftar Temuan Audit BPKP & Tindak Lanjut',
    sektor: ['universal'],
    tipeChart: ['table', 'donut'],
    kategori: 'Kepatuhan & Risiko',
    satuan: 'Status Temuan',
    queryRagContoh: 'Status tindak lanjut rekomendasi audit internal dan BPKP.',
    deskripsi: 'Monitoring penyelesaian rekomendasi SPI dan auditor eksternal pemerintah.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'W-14',
    nama: 'Rasio Likuiditas & Solvabilitas (Current Ratio)',
    sektor: ['universal'],
    tipeChart: ['kpi', 'line'],
    kategori: 'Keuangan',
    satuan: 'Rasio (x)',
    queryRagContoh: 'Rasio lancar aset terhadap kewajiban jangka pendek.',
    deskripsi: 'Kemampuan perusahaan melunasi utang jatuh tempo di bawah satu tahun.',
    defaultLayout: { w: 4, h: 3 },
  },

  // ================= SEKTOR PDAM (P-01 .. P-06) =================
  {
    id: 'P-01',
    nama: 'Tingkat Kehilangan Air Fisik & Komersial (NRW)',
    sektor: ['pdam'],
    tipeChart: ['kpi', 'line', 'gauge'],
    kategori: 'Operasional',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa persentase Non-Revenue Water (NRW) bulan ini dan tren 1 tahun?',
    deskripsi: 'Selisih volume air yang diproduksi di IPA dengan volume air yang tercatat pada meter pelanggan.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'P-02',
    nama: 'Volume Produksi vs Distribusi Air Bersih',
    sektor: ['pdam'],
    tipeChart: ['area', 'line'],
    kategori: 'Operasional',
    satuan: 'Juta m³ / Bulan',
    queryRagContoh: 'Tren debit air produksi instalasi pengolahan air (IPA) vs volume terjual ke pelanggan.',
    deskripsi: 'Perbandingan kapasitas debit air baku yang diolah dengan volume pemakaian riil.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'P-03',
    nama: 'Efisiensi Penagihan Rekening Air (Billing Collection)',
    sektor: ['pdam'],
    tipeChart: ['kpi', 'donut', 'gauge'],
    kategori: 'Keuangan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa persen efisiensi penagihan rekening air pelanggan bulan berjalan?',
    deskripsi: 'Persentase tagihan rekening air terbayar dibanding total invoice yang diterbitkan.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'P-04',
    nama: 'Cakupan Layanan Sambungan Langganan (SL)',
    sektor: ['pdam'],
    tipeChart: ['bar', 'kpi'],
    kategori: 'Pelayanan',
    satuan: 'Jumlah Sambungan (SL)',
    queryRagContoh: 'Jumlah pelanggan aktif per golongan tarif (Rumah Tangga, Niaga, Industri, Sosial).',
    deskripsi: 'Penetrasi sambungan rumah di seluruh zona wilayah administratif PDAM.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'P-05',
    nama: 'Konsumsi Air Rata-rata per Pelanggan',
    sektor: ['pdam'],
    tipeChart: ['line', 'bar'],
    kategori: 'Operasional',
    satuan: 'm³ / SL / Bulan',
    queryRagContoh: 'Rata-rata pemakaian air kubikasi per rumah tangga per bulan.',
    deskripsi: 'Pola konsumsi air bersih masyarakat sebagai dasar perencanaan tarif berkeadilan.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'P-06',
    nama: 'Tekanan Aliran Pipa & Waktu Penanganan Kebocoran',
    sektor: ['pdam'],
    tipeChart: ['table', 'bar'],
    kategori: 'Operasional',
    satuan: 'Jam / Bar',
    queryRagContoh: 'Kecepatan penanganan laporan pipa bocor dan rata-rata tekanan jaringan distribusi.',
    deskripsi: 'Ketangguhan tim teknis URC mengatasi insiden pipa pecah di jalan raya.',
    defaultLayout: { w: 12, h: 4 },
  },

  // ================= SEKTOR PASAR RAKYAT (M-01 .. M-05) =================
  {
    id: 'M-01',
    nama: 'Tingkat Okupansi Kios & Los Pasar',
    sektor: ['pasar'],
    tipeChart: ['kpi', 'donut'],
    kategori: 'Operasional',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa persentase kios dan los yang aktif disewa pedagang saat ini?',
    deskripsi: 'Ketersediaan dan pemanfaatan ruang dagang di seluruh unit pasar binaan perumda.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'M-02',
    nama: 'Realisasi Pendapatan Retribusi Harian Pasar',
    sektor: ['pasar'],
    tipeChart: ['line', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Juta Rupiah',
    queryRagContoh: 'Penerimaan retribusi harian kebersihan, parkir, dan sewa tempat dasaran.',
    deskripsi: 'Penerimaan harian dan bulanan hasil penarikan e-retribusi pedagang.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'M-03',
    nama: 'Fluktuasi Harga Komoditas Pangan Pokok',
    sektor: ['pasar'],
    tipeChart: ['line', 'table'],
    kategori: 'Pelayanan',
    satuan: 'Rp / Kg',
    queryRagContoh: 'Pantauan harga beras, cabai merah, telur, dan minyak goreng 30 hari terakhir.',
    deskripsi: 'Sistem peringatan dini kestabilan harga pangan untuk koordinasi TPID Daerah.',
    defaultLayout: { w: 12, h: 4 },
  },
  {
    id: 'M-04',
    nama: 'Tunggakan Sewa Hak Pakai Kios (SHP)',
    sektor: ['pasar'],
    tipeChart: ['bar', 'table'],
    kategori: 'Keuangan',
    satuan: 'Juta Rupiah',
    queryRagContoh: 'Jumlah tunggakan perpanjangan izin hak pakai lapak per unit pasar.',
    deskripsi: 'Monitoring kepatuhan administrasi sewa jangka panjang oleh pemilik kios.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'M-05',
    nama: 'Volume Pengelolaan Sampah Harian Pasar',
    sektor: ['pasar'],
    tipeChart: ['kpi', 'bar'],
    kategori: 'Operasional',
    satuan: 'Ton / Hari',
    queryRagContoh: 'Berapa ton sampah organik dan anorganik terkelola setiap hari di pasar induk?',
    deskripsi: 'Kebersihan lingkungan dan efisiensi pengangkutan residu pasar ke TPA.',
    defaultLayout: { w: 6, h: 4 },
  },

  // ================= SEKTOR BANK DAERAH (B-01 .. B-06) =================
  {
    id: 'B-01',
    nama: 'Rasio Kredit Macet Bermasalah (NPL Gross / Net)',
    sektor: ['bank'],
    tipeChart: ['kpi', 'line'],
    kategori: 'Kepatuhan & Risiko',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa Non-Performing Loan (NPL) gross dan tren kualitas aset kredit?',
    deskripsi: 'Indikator kesehatan kredit utama perbankan daerah sesuai regulasi OJK (ambang aman < 5%).',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'B-02',
    nama: 'Penyaluran Kredit Produktif UMKM vs Konsumtif',
    sektor: ['bank'],
    tipeChart: ['bar', 'donut'],
    kategori: 'Operasional',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Komposisi penyaluran kredit ASN vs kredit modal kerja UMKM binaan Pemda.',
    deskripsi: 'Dukungan permodalan bank pembangunan daerah terhadap pengusaha lokal.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'B-03',
    nama: 'Penghimpunan Dana Pihak Ketiga (DPK)',
    sektor: ['bank'],
    tipeChart: ['area', 'line'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Pertumbuhan simpanan tabungan, giro kas daerah, dan deposito berjangka.',
    deskripsi: 'Kekuatan likuiditas simpanan masyarakat dan dana kelolaan APBD di BPD.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'B-04',
    nama: 'Loan to Deposit Ratio (LDR)',
    sektor: ['bank'],
    tipeChart: ['kpi', 'bullet-target'],
    kategori: 'Kepatuhan & Risiko',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa rasio LDR likuiditas pembiayaan bank daerah saat ini?',
    deskripsi: 'Keseimbangan antara total pinjaman yang disalurkan dengan dana masyarakat.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'B-05',
    nama: 'Efisiensi Operasional (BOPO & NIM)',
    sektor: ['bank'],
    tipeChart: ['line', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Tren rasio Beban Operasional terhadap Pendapatan Operasional (BOPO) dan Net Interest Margin.',
    deskripsi: 'Efisiensi biaya bunga dan biaya operasional terhadap perolehan margin bunga bersih.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'B-06',
    nama: 'Kecukupan Modal Minimum (CAR)',
    sektor: ['bank'],
    tipeChart: ['kpi', 'line'],
    kategori: 'Kepatuhan & Risiko',
    satuan: 'Persen (%)',
    queryRagContoh: 'Rasio Capital Adequacy Ratio (CAR) bank terhadap aset tertimbang menurut risiko.',
    deskripsi: 'Bantalan ketahanan modal bank daerah untuk menyerap potensi kerugian usaha.',
    defaultLayout: { w: 6, h: 4 },
  },

  // ================= SEKTOR RUMAH SAKIT DAERAH / RSUD (R-01 .. R-05) =================
  {
    id: 'R-01',
    nama: 'Tingkat Keterisian Tempat Tidur (BOR Rawat Inap)',
    sektor: ['rsud'],
    tipeChart: ['kpi', 'line'],
    kategori: 'Operasional',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa Bed Occupancy Rate (BOR) bangsal rawat inap saat ini?',
    deskripsi: 'Pemanfaatan bed rawat inap rumah sakit (standar Kemenkes ideal 60% - 85%).',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'R-02',
    nama: 'Kunjungan Poliklinik Rawat Jalan vs IGD',
    sektor: ['rsud'],
    tipeChart: ['line', 'area'],
    kategori: 'Pelayanan',
    satuan: 'Pasien / Hari',
    queryRagContoh: 'Tren volume pasien rawat jalan spesialis dan pasien darurat IGD harian.',
    deskripsi: 'Volume beban kerja dokter dan perawat dalam melayani pasien faskes rujukan daerah.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'R-03',
    nama: 'Komposisi Penjamin Pasien (BPJS vs Umum)',
    sektor: ['rsud'],
    tipeChart: ['donut', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Proporsi pasien peserta BPJS Kesehatan PBI, Non-PBI, asuransi swasta, dan bayar umum.',
    deskripsi: 'Struktur sumber pembiayaan tindakan medis rumah sakit daerah.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'R-04',
    nama: 'Realisasi & Piutang Klaim BPJS Kesehatan',
    sektor: ['rsud'],
    tipeChart: ['bar', 'table'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Klaim BPJS yang telah terverifikasi, dibayarkan, dan status berkas pending claim.',
    deskripsi: 'Arus penerimaan kas pendapatan klaim tarif INA-CBGs dari BPJS Kesehatan.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'R-05',
    nama: 'Rata-rata Lama Rawat (ALOS) & Waktu Tunggu Farmasi',
    sektor: ['rsud'],
    tipeChart: ['table', 'bar'],
    kategori: 'Pelayanan',
    satuan: 'Hari / Menit',
    queryRagContoh: 'Average Length of Stay (ALOS) pasien rawat inap dan waktu racik obat resep kronis.',
    deskripsi: 'Standar mutu pelayanan klinis dan kecepatan pengambilan obat di apotek faskes.',
    defaultLayout: { w: 12, h: 4 },
  },

  // ================= SEKTOR TRANSPORTASI DAERAH (T-01 .. T-04) =================
  {
    id: 'T-01',
    nama: 'Tingkat Keterisian Penumpang (Load Factor Koridor)',
    sektor: ['transportasi'],
    tipeChart: ['kpi', 'line'],
    kategori: 'Operasional',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa rata-rata load factor penumpang bus rapid transit (BRT) per koridor?',
    deskripsi: 'Kepadatan penumpang per armada bus dibanding kapasitas tempat duduk maksimal.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'T-02',
    nama: 'Ketepatan Waktu Kedatangan Bus (On-Time Performance)',
    sektor: ['transportasi'],
    tipeChart: ['kpi', 'bar'],
    kategori: 'Pelayanan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Persentase armada bus yang tiba di halte sesuai jadwal headway (< 10 menit).',
    deskripsi: 'Keandalan jadwal operasional transportasi publik melayani mobilitas warga.',
    defaultLayout: { w: 4, h: 3 },
  },
  {
    id: 'T-03',
    nama: 'Realisasi Subsidi PSO Pemda vs Pendapatan Tiket (Farebox)',
    sektor: ['transportasi'],
    tipeChart: ['bar', 'line'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Berapa subsidi Public Service Obligation per km tempuh dibanding pendapatan tiket.',
    deskripsi: 'Efisiensi alokasi anggaran subsidi transportasi massal per kilometer operasional.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'T-04',
    nama: 'Kesiapan Armada Operasional (Vehicle Availability)',
    sektor: ['transportasi'],
    tipeChart: ['donut', 'table'],
    kategori: 'Operasional',
    satuan: 'Armada Siap Jalan',
    queryRagContoh: 'Jumlah bus jalan beroperasi, bus cadangan pool, dan bus dalam perbaikan bengkel.',
    deskripsi: 'Kesiapan teknis armada melayani rute koridor tanpa gangguan mogok di jalan.',
    defaultLayout: { w: 8, h: 4 },
  },
  // ================= VISUALISASI LANJUTAN (X-01 .. X-05) =================
  // Tipe gauge & heatmap — pola KPI dashboard: konteks target, perbandingan antar unit.
  {
    id: 'X-01',
    nama: 'Speedometer Capaian Target RKAP',
    sektor: ['universal'],
    tipeChart: ['gauge', 'kpi'],
    kategori: 'Keuangan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa persen capaian realisasi pendapatan terhadap target RKAP tahun berjalan?',
    deskripsi: 'Gauge jarum capaian target RKAP — insight cepat "sudah sejauh mana" dalam satu pandangan.',
    defaultLayout: { w: 4, h: 4 },
  },
  {
    id: 'X-02',
    nama: 'Gauge Capaian Target NRW Peraturan',
    sektor: ['pdam'],
    tipeChart: ['gauge', 'kpi'],
    kategori: 'Operasional',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa NRW aktual dibanding batas maksimal yang diizinkan peraturan BPKP?',
    deskripsi: 'Gauge posisi NRW aktual terhadap ambang regulasi (mis. target ≤ 20%).',
    defaultLayout: { w: 4, h: 4 },
  },
  {
    id: 'X-03',
    nama: 'Heatmap Kinerja antar Unit Kerja',
    sektor: ['universal'],
    tipeChart: ['heatmap', 'table'],
    kategori: 'Operasional',
    satuan: 'Skor Kinerja',
    queryRagContoh: 'Perbandingan capaian indikator kinerja tiap unit kerja per triwulan.',
    deskripsi: 'Peta panas unit × periode — langsung terlihat sel mana yang di bawah standar.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'X-04',
    nama: 'Heatmap Konsumsi Air per Zona Layanan',
    sektor: ['pdam'],
    tipeChart: ['heatmap'],
    kategori: 'Operasional',
    satuan: 'm³ / Bulan',
    queryRagContoh: 'Pola konsumsi air bersih tiap zona distribusi per bulan selama setahun.',
    deskripsi: 'Matriks zona × bulan untuk mengenali pola musiman dan anomali pemakaian.',
    defaultLayout: { w: 8, h: 5 },
  },
  {
    id: 'X-05',
    nama: 'Gauge Kepatuhan Standar Layanan Minimal',
    sektor: ['universal', 'pdam', 'rsud'],
    tipeChart: ['gauge'],
    kategori: 'Pelayanan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Berapa capaian indikator standar pelayanan minimal wajib periode ini?',
    deskripsi: 'Gauge kepatuhan SPM — konteks langsung untuk laporan ke BPKP dan Pemda.',
    defaultLayout: { w: 4, h: 4 },
  },

  // ============ VISUALISASI LANJUTAN (X-06 .. X-15) ============
  {
    id: 'X-06',
    nama: 'Funnel Tahapan Realisasi Anggaran',
    sektor: ['universal'],
    tipeChart: ['funnel', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Tahapan realisasi anggaran dari pagu, komitmen, sampai pencairan kas.',
    deskripsi: 'Funnel penyusutan nilai pada tiap tahap proses anggaran — memperlihatkan kebocoran tahap.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'X-07',
    nama: 'Waterfall Jembatan Laba (Profit Bridge)',
    sektor: ['universal'],
    tipeChart: ['waterfall', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Uraikan perubahan laba dari pendapatan, beban, sampai laba bersih akhir periode.',
    deskripsi: 'Waterfall perubahan dari nilai awal ke akhir — standar analisis jembatan laba.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'X-08',
    nama: 'Scatter Korelasi Produksi vs Beban',
    sektor: ['universal'],
    tipeChart: ['scatter', 'bubble'],
    kategori: 'Operasional',
    satuan: 'Campuran',
    queryRagContoh: 'Hubungan volume produksi/layanan dengan beban operasional per unit kerja.',
    deskripsi: 'Sebaran titik dua variabel — mengenali korelasi, klaster, dan pencilan.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'X-09',
    nama: 'Bubble Kinerja (Volume, Nilai, Efisiensi)',
    sektor: ['universal'],
    tipeChart: ['bubble', 'scatter'],
    kategori: 'Operasional',
    satuan: 'Campuran',
    queryRagContoh: 'Perbandingan unit kerja: volume layanan, pendapatan, dan ukuran beban.',
    deskripsi: 'Bubble menambah dimensi ketiga (ukuran) di atas sebaran dua variabel.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'X-10',
    nama: 'Histogram Distribusi Nilai Transaksi',
    sektor: ['universal'],
    tipeChart: ['histogram', 'bar'],
    kategori: 'Keuangan',
    satuan: 'Frekuensi',
    queryRagContoh: 'Sebaran frekuensi nilai transaksi/tagihan untuk melihat pola dan rentang ekstrem.',
    deskripsi: 'Histogram distribusi frekuensi — menampakkan bentuk sebaran dan pencilan.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'X-11',
    nama: 'Box Plot Sebaran per Unit Kerja',
    sektor: ['universal'],
    tipeChart: ['boxplot', 'histogram'],
    kategori: 'Operasional',
    satuan: 'Campuran',
    queryRagContoh: 'Perbandingan sebaran capaian antar unit kerja beserta pencilan.',
    deskripsi: 'Box plot ringkas distribusi & outlier tiap kelompok — kuat untuk audit.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'X-12',
    nama: 'Treemap Komposisi Beban per Unit',
    sektor: ['universal'],
    tipeChart: ['treemap', 'donut'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Komposisi dan proporsi beban tiap unit kerja dalam satu periode.',
    deskripsi: 'Treemap hierarki komposisi — langsung terlihat pos yang menyerap anggaran terbesar.',
    defaultLayout: { w: 6, h: 4 },
  },
  {
    id: 'X-13',
    nama: 'Sankey Aliran Dana/Dokumen',
    sektor: ['universal'],
    tipeChart: ['sankey', 'funnel'],
    kategori: 'Keuangan',
    satuan: 'Rupiah (Miliar)',
    queryRagContoh: 'Aliran dana dari sumber penerimaan ke pos belanja antar kategori.',
    deskripsi: 'Sankey aliran antar kategori — memperlihatkan jalur dan besaran perpindahan nilai.',
    defaultLayout: { w: 8, h: 5 },
  },
  {
    id: 'X-14',
    nama: 'Combo Tren & Rasio (Dual Axis)',
    sektor: ['universal'],
    tipeChart: ['combo', 'line'],
    kategori: 'Keuangan',
    satuan: 'Campuran',
    queryRagContoh: 'Tren nilai absolut berdampingan dengan rasio persentase pada sumbu terpisah.',
    deskripsi: 'Combo batang + garis dua sumbu — membandingkan metrik beda satuan dalam satu grafik.',
    defaultLayout: { w: 8, h: 4 },
  },
  {
    id: 'X-15',
    nama: 'Gantt Jadwal Program & Proyek',
    sektor: ['universal'],
    tipeChart: ['gantt', 'table'],
    kategori: 'Operasional',
    satuan: 'Tanggal',
    queryRagContoh: 'Jadwal pelaksanaan program/proyek beserta tanggal mulai dan selesai.',
    deskripsi: 'Gantt timeline jadwal proyek — memantau rentang waktu & progres pekerjaan.',
    defaultLayout: { w: 8, h: 5 },
  },
  {
    id: 'X-16',
    nama: 'Peta Sebaran Wilayah (Filled Map)',
    sektor: ['universal'],
    tipeChart: ['map', 'table'],
    kategori: 'Pelayanan',
    satuan: 'Campuran',
    queryRagContoh: 'Sebaran nilai indikator per wilayah/kabupaten/kota.',
    deskripsi: 'Peta choropleth persebaran nilai antar wilayah — memperlihatkan disparitas geografis.',
    defaultLayout: { w: 8, h: 5 },
  },
  {
    id: 'X-17',
    nama: 'Radar Profil Multi-Indikator',
    sektor: ['universal'],
    tipeChart: ['radar', 'bar'],
    kategori: 'Operasional',
    satuan: 'Skor',
    queryRagContoh: 'Profil capaian beberapa indikator kinerja sekaligus untuk satu unit.',
    deskripsi: 'Radar membandingkan profil multi-indikator — cepat melihat dimensi kuat & lemah.',
    defaultLayout: { w: 6, h: 5 },
  },
  {
    id: 'X-18',
    nama: 'Pie Komposisi Sederhana',
    sektor: ['universal'],
    tipeChart: ['pie', 'donut'],
    kategori: 'Keuangan',
    satuan: 'Persen (%)',
    queryRagContoh: 'Komposisi proporsi beberapa kategori utama dalam satu periode.',
    deskripsi: 'Pie chart komposisi — versi padat untuk potret proporsi cepat.',
    defaultLayout: { w: 5, h: 4 },
  },
];
